### ISSUE TITLE
Panic at 'index out of bounds: the len is 0 but the index is 0'

### ISSUE THREAD

**Issue by Confusion** [rbspy/rbspy#141]
Thanks for rbspy! 

When running a `RUST_BACKTRACE=1 rbspy record -- bundle exec rspec -t @some_tag` I'm seeing the trace below. The specs in question use rails, capybara, thin and poltergeist to execute some 'integration' specs, so plenty of things with threads going on. Unfortunately I cannot share our setup and I haven't been able to reproduce it using something simpler. Just trying to pinpoint the exact spec that fails (via rspec -f d or via puts) makes the panic go away.

So this issue is mainly to document that users may currently encounter this error, at least when using rbspy 0.2.4, Ruby 2.5.0, Rails 4.2.10.

````
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /checkout/src/liballoc/vec.rs:1551:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic_bounds_check
             at libcore/panicking.rs:58
  10: rbspy::ui::summary::Stats::add_function_name
  11: rbspy::do_main
  12: rbspy::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  17: main
````

**Comment by jvns** [comment]
@Confusion Can you test https://github.com/rbspy/rbspy/pull/142 and see if it helps? 

i'm guessing this is a sign of another underlying issue, but knowing what happens when you try #142 hopefully will shed some light.

Does this happen if you run `rbspy snapshot` on the running process once, or does it only panic after running for some amount of time?

**Comment by Confusion** [comment]
Thanks, #142 prevents the panic. 

It only happens after running for some time, when recording. I haven't seen it when taking snapshots, but I probably just haven't managed to take a snapshot at a 'wrong' time.

BTW, I also verified that current HEAD reproduces the panic, so it's really just #142 that makes the difference.
