### ISSUE TITLE
Error "No stack counts found" when trying to profile ruby 2.6.3 by pid

### ISSUE THREAD

**Issue by Frederik-Baetens** [rbspy/rbspy#226]
I ran `rbspy record --pid 35` and got the error:

```
Press Ctrl+C to stop
Wrote raw data to /root/.cache/rbspy/records/rbspy-2019-08-29-E3Qc4TJIj7.raw.gz
Writing formatted output to /root/.cache/rbspy/records/rbspy-2019-08-29-cTpezCRXzx.flamegraph.svg
[2019-08-29T17:04:44Z ERROR inferno::flamegraph] No stack counts found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: StringError("No stack counts found") })', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

This was in a docker container on kubernetes, but i don't think that should matter since i'm running rbspy in the same container as the process i'm trying to profile.

Running with rbspy record cmd does work, but isn't very useful for us since the process i'm trying to look at is a web server that spawns 2 other processes which do the actual work.

**Comment by dfuentes77** [comment]
I'm getting the same error with ruby 2.5.1 on ubuntu linux:
```
$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

I'm trying to profile a running `sidekiq` process:
```
$ ps axufww|grep sidekiq
deploy   11501 36.4  7.8 837904 604236 ?       Ssl  Aug30 2109:44 sidekiq 5.1.3 api [19 of 25 busy]
deploy   11507 14.7 29.6 2556012 2272200 ?     Ssl  Aug30 855:20 sidekiq 5.1.3 api [25 of 25 busy]
deploy   31191 75.9 35.3 2917784 2709544 ?     Ssl  Sep01 2177:11 sidekiq 5.1.3 api [22 of 25 busy]
```

with this output
```
$ ./rbspy record --pid 11501
Press Ctrl+C to stop
Wrote raw data to /home/<username>/.cache/rbspy/records/rbspy-2019-09-03-tCmJMnmfPl.raw.gz
Writing formatted output to /home/<username>/.cache/rbspy/records/rbspy-2019-09-03-3iucfFkDnH.flamegraph.svg
[2019-09-03T22:08:45Z ERROR inferno::flamegraph] No stack counts found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: StringError("No stack counts found") })', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by b0nn1e** [comment]
I have same problem.
`$ rbspy --version
rbspy 0.3.7
$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-
$ rbspy record --pid 3632
Press Ctrl+C to stop
Wrote raw data to /home/andand/.cache/rbspy/records/rbspy-2019-09-07-8XaFUdCPGS.raw.gz
Writing formatted output to /home/andand/.cache/rbspy/records/rbspy-2019-09-07-xVPSDqOohm.flamegraph.svg
[2019-09-07T11:58:20Z ERROR inferno::flamegraph] No stack counts found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: "No stack counts found" })', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
`

**Comment by DanielHeath** [comment]
IIRC you need to run as root on linux

**Comment by belt** [comment]
Running as root on alpine within doesn't help

**Comment by doudou** [comment]
Same here, but doing a `record COMMAND` ... could it be that rbspy starts sampling before the ruby process is properly setup ?

Weirdly, I managed to get ONE trace, and then it started failing every single time.

**Comment by prettycoder** [comment]
I had the same problem and found help in the gitter chat room:
If you are using **docker** you have to add `--cap-add=SYS_PTRACE` to `docker run` or something similar in your docker-compose file.

I support the suggestion from the chatroom that this should be documented somewhere.

**Comment by doudou** [comment]
Not using docker :(

Got some traces yesterday. It seems to be random.

**Comment by ric2b** [comment]
Same issue on a Mac, not using docker:

```bash
>> sudo rbspy record -- bundle exec ruby -e "puts ('hello world')"
Dropping permissions: running Ruby command as user ricardoamendoeira
Press Ctrl+C to stop
Wrote raw data to /Users/myusername/.cache/rbspy/records/rbspy-2020-03-04-T07pRqovQP.raw.gz
Writing formatted output to /Users/myusername/.cache/rbspy/records/rbspy-2020-03-04-XjvCVm27HH.flamegraph.svg
[2020-03-04T12:53:51Z ERROR inferno::flamegraph] No stack counts found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: "No stack counts found" })', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
hello world
```

MacOS 10.14.6
Ruby 2.6.1

**Comment by f3ndot** [comment]
Issue appears in macOS 10.15.4 (Catalina) as well:

```
     ~/Code/rbspy     master !1 ▓▒░
❯ sudo --preserve-env ~/Code/rbspy/target/release/rbspy record -- ruby -e "puts ('hello world')"
Dropping permissions: running Ruby command as user justin
Press Ctrl+C to stop
Wrote raw data to /Users/justin/.cache/rbspy/records/rbspy-2020-05-04-nRswYAp8Pi.raw.gz
Writing formatted output to /Users/justin/.cache/rbspy/records/rbspy-2020-05-04-EnO63Soowc.flamegraph.svg
[2020-05-04T14:19:41Z ERROR inferno::flamegraph] No stack counts found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: "No stack counts found" })', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

     ~/Code/rbspy     master !1 ▓▒░
❯ hello world
```

Ruby 2.7.1, 2.6.6, 2.6.3 all via `rbenv`. Tried in oh-my-zsh and vanilla bash environments.

**Comment by jarthod** [comment]
Same problem for me when trying to run a simple local ruby script to test my changes (#276):
```
bigbourin@desktop [rbspy] (add-flamegraph-precision-option) > ./target/debug/rbspy record -- ruby ci/ruby-programs/recurse-sleep.rb 
Press Ctrl+C to stop
Wrote raw data to /home/bigbourin/.cache/rbspy/records/rbspy-2021-04-12-1umsHKhj8s.raw.gz
Writing formatted output to /home/bigbourin/.cache/rbspy/records/rbspy-2021-04-12-Z2FftD3Y1s.flamegraph.svg
[2021-04-12T14:58:28Z ERROR inferno::flamegraph] No stack counts found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: "No stack counts found" })', src/ui/flamegraph.rs:40:89
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The ruby script alone works fine and returns after 10 seconds without error.
```
> ruby ci/ruby-programs/recurse-sleep.rb
>

```
The root cause is likely different than previous reports here but it looks like the error message is always the same no matter what happened to the started command (maybe it crashed? maybe there was an exception?) #268 would probably help here if we could have a bit more details about the failed process (e.g. exist status, stderr/stdout messages?)

**Comment by acj** [comment]
@jarthod Can you share the script that you're running? And the ruby and platform versions? The script probably isn't the issue, but it may help us diagnose this, especially if it fails somewhat consistently.

**Comment by jarthod** [comment]
Sure, I just shared this script in https://github.com/rbspy/rbspy/pull/276#issuecomment-818036952
```ruby
def recurse_sleep(seconds)
  return if seconds <= 0.00001
  sleep(seconds/2.0)
  recurse_sleep(seconds/2.0)
end

recurse_sleep(30)
```

But I have the same problem with any ruby script already in the repo so it's not related to the script itself, likely to my OS (Ubuntu 20.10) or something else but it's hard for me to debug if `rbspy` doesn't let me know what is the problem for it.

**Comment by acj** [comment]
Thanks. Which ruby version(s)? (Sorry to nag, but it's often a key piece of the puzzle)

Yeah, the current error message is very unhelpful. Surfacing more precise error info is on my to-do list after 0.5 goes out.

Is the error intermittent for you? You were able to generate some flamegraphs for the PR, so I'm curious whether you're using another machine or are retrying until it works.

If you get a chance, please try running rbspy with `sudo`, and maybe also with debug logging: `sudo RUST_LOG=debug ./target/debug/rbspy ...`. The output may very noisy with diagnostic info, so feel free to link to a gist or pastebin if you still have the issue and are willing to provide the logs.

**Comment by jarthod** [comment]
No problem, I definitely omitted some important details.

I was using ruby 2.6.4 installed with rbenv:
```
bigbourin@desktop [rbspy] (add-flamegraph-precision-option) > ruby --version
ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-linux]
bigbourin@desktop [rbspy] (add-flamegraph-precision-option) > rbenv versions
  2.4.6
  2.5.8
* 2.6.4 (set by /home/bigbourin/.rbenv/version)
  2.6.6
  2.7.2
  jruby-9.2.14.0
```

The error is **not** intermittent for me, to generate the flamegraphs in my PR I actually started the ruby script on the side and used `sudo rbspy record --pid xxxx` instead, this version worked without problem for me (requires root access though).

I tried running `rbenv record` with the command as root but as I don't have any root install of `ruby` this doesn't work at first:
```
bigbourin@desktop [rbspy] (add-flamegraph-precision-option) > sudo ./target/debug/rbspy record -- ruby ci/ruby-programs/recurse-sleep.rb 
Dropping permissions: running Ruby command as user bigbourin
Error. Causes: 
- No such file or directory (os error 2)
No such file or directory (os error 2)
```
(error message is also not great here ^^ but a bit better)

But if I specify the exact path from rbenv user-land install or ruby, like this:
```
sudo ./target/debug/rbspy record -- /home/bigbourin/.rbenv/shims/ruby ci/ruby-programs/recurse-sleep.rb
```
Then it works fine, with the debug mode enabled I managed to catch this before the interface switches to stackframes but as this is working fine I guess not very helpful:
```
[2021-04-12T19:16:23Z DEBUG rbspy::core::address_finder::os_impl] symbol: Symbol: Value: 0x002be61b Size: 0x0006 Type: data object Bind: global Vis: default Section: 14 Name: ruby_version
[2021-04-12T19:16:23Z DEBUG rbspy::core::address_finder::os_impl] load header: Program Header: Type: LOAD Offset: 0x0002b000 VirtAddr: 0x0002b000 PhysAddr: 0x0002b000 FileSize: 0x259f51 MemSize: 0x259f51 Flags: R E Align: 0x1000
[2021-04-12T19:16:23Z DEBUG rbspy::core::address_finder::os_impl] symbol: Symbol: Value: 0x00385580 Size: 0x0008 Type: data object Bind: global Vis: default Section: 24 Name: ruby_current_execution_context_ptr
[2021-04-12T19:16:23Z DEBUG rbspy::core::address_finder::os_impl] load header: Program Header: Type: LOAD Offset: 0x0002b000 VirtAddr: 0x0002b000 PhysAddr: 0x0002b000 FileSize: 0x259f51 MemSize: 0x259f51 Flags: R E Align: 0x1000
[2021-04-12T19:16:23Z DEBUG rbspy::core::initialize] version: 2.6.4
[2021-04-12T19:16:23Z DEBUG rbspy::core::address_finder::os_impl] symbol: Symbol: Value: 0x00385588 Size: 0x0008 Type: data object Bind: global Vis: default Section: 24 Name: ruby_current_vm_ptr
[2021-04-12T19:16:23Z DEBUG rbspy::core::address_finder::os_impl] load header: Program Header: Type: LOAD Offset: 0x0002b000 VirtAddr: 0x0002b000 PhysAddr: 0x0002b000 FileSize: 0x259f51 MemSize: 0x259f51 Flags: R E Align: 0x1000
[2021-04-12T19:16:23Z DEBUG rbspy::core::address_finder::os_impl] symbol: Symbol: Value: 0x00377960 Size: 0x0020 Type: data object Bind: local Vis: default Section: 23 Name: global_symbols
[2021-04-12T19:16:23Z DEBUG rbspy::core::address_finder::os_impl] load header: Program Header: Type: LOAD Offset: 0x0002b000 VirtAddr: 0x0002b000 PhysAddr: 0x0002b000 FileSize: 0x259f51 MemSize: 0x259f51 Flags: R E Align: 0x1000
```

I also tried with the same exact ruby path without sudo but got the same error:
```
bigbourin@desktop [rbspy] (add-flamegraph-precision-option) > ./target/debug/rbspy record -- /home/bigbourin/.rbenv/shims/ruby ci/ruby-programs/recurse-sleep.rb 
Press Ctrl+C to stop
Wrote raw data to /home/bigbourin/.cache/rbspy/records/rbspy-2021-04-12-LZqoKhDSZP.raw.gz
Writing formatted output to /home/bigbourin/.cache/rbspy/records/rbspy-2021-04-12-svlBCyKhDq.flamegraph.svg
[2021-04-12T19:13:12Z ERROR inferno::flamegraph] No stack counts found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: "No stack counts found" })', src/ui/flamegraph.rs:40:89
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

with `RUST_LOG=debug` I don't see more output:
```
bigbourin@desktop [rbspy] (add-flamegraph-precision-option) > RUST_LOG=debug ./target/debug/rbspy record -- ruby ci/ruby-programs/recurse-sleep.rb 
Press Ctrl+C to stop
Wrote raw data to /home/bigbourin/.cache/rbspy/records/rbspy-2021-04-12-BZVWh866NI.raw.gz
Writing formatted output to /home/bigbourin/.cache/rbspy/records/rbspy-2021-04-12-gMXXHRY6EC.flamegraph.svg
[2021-04-12T19:14:12Z ERROR inferno::flamegraph] No stack counts found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: "No stack counts found" })', src/ui/flamegraph.rs:40:89
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

And with `RUST_BACKTRACE` I get the same - I believe - unhelpful backtrace already shown before which is only related to the lack of data:
```
bigbourin@desktop [rbspy] (add-flamegraph-precision-option) > RUST_BACKTRACE=full ./target/debug/rbspy record -- ruby ci/ruby-programs/recurse-sleep.rb 
Press Ctrl+C to stop
Wrote raw data to /home/bigbourin/.cache/rbspy/records/rbspy-2021-04-12-kNSrxae943.raw.gz
Writing formatted output to /home/bigbourin/.cache/rbspy/records/rbspy-2021-04-12-2JGmilBF4E.flamegraph.svg
[2021-04-12T19:14:50Z ERROR inferno::flamegraph] No stack counts found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: "No stack counts found" })', src/ui/flamegraph.rs:40:89
stack backtrace:
   0:     0x55a404bea1cc - std::backtrace_rs::backtrace::libunwind::trace::h87bbdc8ae314e5a4
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55a404bea1cc - std::backtrace_rs::backtrace::trace_unsynchronized::h779de2081f0fe77d
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55a404bea1cc - std::sys_common::backtrace::_print_fmt::h7f9f27f2b4d4cdf1
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:79
   3:     0x55a404bea1cc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf95d19d7937b7307
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:58
   4:     0x55a404c215cf - core::fmt::write::h31ddd5324183dd8d
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/core/src/fmt/mod.rs:1082
   5:     0x55a404be3a67 - std::io::Write::write_fmt::h6553ae225ae21934
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/io/mod.rs:1514
   6:     0x55a404c00c90 - std::sys_common::backtrace::_print::h6d7cde6fb59a3272
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:61
   7:     0x55a404c00c90 - std::sys_common::backtrace::print::h024fb5a1f254b027
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:48
   8:     0x55a404c00c90 - std::panicking::default_hook::{{closure}}::h008654930ff7c19c
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:200
   9:     0x55a404c009ee - std::panicking::default_hook::h611ef89f1ca4afb7
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:219
  10:     0x55a404c01273 - std::panicking::rust_panic_with_hook::h4dfeaf97568ec250
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:569
  11:     0x55a404bea609 - std::panicking::begin_panic_handler::{{closure}}::hf55586f621f9c415
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:476
  12:     0x55a404bea31c - std::sys_common::backtrace::__rust_end_short_backtrace::hbddda20e4c1f6fd7
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:153
  13:     0x55a404c00e82 - rust_begin_unwind
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:475
  14:     0x55a404c20fe1 - core::panicking::panic_fmt::he4c3f055751e8cea
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/core/src/panicking.rs:85
  15:     0x55a404c21073 - core::result::unwrap_failed::h24cfbc9782f4fe17
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/core/src/result.rs:1220
  16:     0x55a40447f4da - core::result::Result<T,E>::unwrap::hce1f5e0588c294ce
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/core/src/result.rs:973
  17:     0x55a40454a3e6 - rbspy::ui::flamegraph::Stats::write::hd01d657e25d27161
                               at /home/bigbourin/work/rbspy/src/ui/flamegraph.rs:40
  18:     0x55a4043609d2 - <rbspy::ui::output::Flamegraph as rbspy::ui::output::Outputter>::complete::h24930236c6a09703
                               at /home/bigbourin/work/rbspy/src/ui/output.rs:26
  19:     0x55a4042fd1c3 - rbspy::parallel_record::h301cb69d9c74e170
                               at /home/bigbourin/work/rbspy/src/main.rs:579
  20:     0x55a4042fa7de - rbspy::do_main::h3923371140e8b6de
                               at /home/bigbourin/work/rbspy/src/main.rs:193
  21:     0x55a4042fac1c - rbspy::main::hfdc2ec57c6070b49
                               at /home/bigbourin/work/rbspy/src/main.rs:284
  22:     0x55a40430d21b - core::ops::function::FnOnce::call_once::hcc2bcbacf62dd466
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/core/src/ops/function.rs:227
  23:     0x55a4043a111e - std::sys_common::backtrace::__rust_begin_short_backtrace::hda350080c5809864
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:137
  24:     0x55a404271fd1 - std::rt::lang_start::{{closure}}::hf44b308ad6a9d3c4
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/rt.rs:66
  25:     0x55a404c015cc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h198b3348bc6fe6ff
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/core/src/ops/function.rs:259
  26:     0x55a404c015cc - std::panicking::try::do_call::hb35a1579447c1de7
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:373
  27:     0x55a404c015cc - std::panicking::try::h5fe941721b9f82d8
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:337
  28:     0x55a404c015cc - std::panic::catch_unwind::h5184cddbb930bb79
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/panic.rs:379
  29:     0x55a404c015cc - std::rt::lang_start_internal::ha12a50f31e33d94f
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/rt.rs:51
  30:     0x55a404271fa7 - std::rt::lang_start::hed61f301f935e1f5
                               at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/rt.rs:65
  31:     0x55a40430173a - main
  32:     0x7f05252fbcb2 - __libc_start_main
  33:     0x55a4042040ce - _start
  34:                0x0 - <unknown>
```

**Comment by acj** [comment]
With the release of rbspy 0.6, we should print more specific errors instead of "No stack counts found". We've also fixed several initialization bugs that may have been the root cause for some of you. If you still have trouble after upgrading, please open a new issue with the specific error message that you're getting.

Thanks for your patience and feedback, everyone 👍

**Comment by Frederik-Baetens** [comment]
Thanks for working on this amazing project, you are awesome ❤️
