### ISSUE TITLE
Ruby version not supported yet: 2.7.0

### ISSUE THREAD

**Issue by gwenhael-le-moine** [rbspy/rbspy#244]
(rbspy compiled from master today.)

```
Press Ctrl+C to stop
thread '<unnamed>' panicked at 'Ruby version not supported yet: 2.7.0. Please create a GitHub issue and we'll fix it!', src/core/initialize.rs:340:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Wrote raw data to /home/XXX/.cache/rbspy/records/rbspy-2020-01-14-nPi9lgQl9u.raw.gz
Writing formatted output to /home/XXX/.cache/rbspy/records/rbspy-2020-01-14-hB1FCDBIdN.flamegraph.svg
[2020-01-14T14:51:41Z ERROR inferno::flamegraph] No stack counts found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: "No stack counts found" })', src/libcore/result.rs:1165:5
```

**Comment by electron0zero** [comment]
getting same error when using with ruby 2.6.5

```sh
deploy@suraj:~/clarisights/current$ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
deploy@suraj:~/clarisights/current$ sudo rbspy record --pid 1693
Press Ctrl+C to stop
Wrote raw data to /home/deploy/.cache/rbspy/records/rbspy-2020-02-09-6F9c7iQHjq.raw.gz
Writing formatted output to /home/deploy/.cache/rbspy/records/rbspy-2020-02-09-DZfcYG5xDY.flamegraph.svg
[2020-02-09T20:17:38Z ERROR inferno::flamegraph] No stack counts found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: "No stack counts found" })', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
deploy@suraj:~/clarisights/current$ 
```
