### ISSUE TITLE
[linux] Buggy tests, processes not killed

### ISSUE THREAD

**Issue by Horki** [rbspy/rbspy#333]
Kernel Release: 5.12.15-arch1-1

On Linux, sometimes when I run tests, and some test fails, due to panics, `process::kill` is never invoked, and they keep running in the background.

PS This also happens if I enforce to run single-threaded tests via`cargo test --release -- --test-threads=1`

`% cargo test --release`

```
running 27 tests
test core::initialize::test_initialize_with_disallowed_process ... ok
test core::initialize::test_initialize_with_nonexistent_process ... ok
test core::ruby_version::tests::test_get_ruby_stack_trace_1_9_3 ... ok
test core::ruby_version::tests::test_get_ruby_stack_trace_2_4_0 ... ok
test core::ruby_version::tests::test_get_ruby_stack_trace_2_5_0 ... ok
test core::ruby_version::tests::test_get_ruby_stack_trace_2_1_6 ... ok
test core::initialize::test_get_trace ... FAILED
test core::initialize::test_get_exec_trace ... FAILED
test core::initialize::test_current_thread_address ... FAILED
test test_output_filename ... ok
./ci/ruby-programs/ruby_exec.rb:4:in `readline': end of file reached (EOFError)
        from ./ci/ruby-programs/ruby_exec.rb:4:in `<main>'
test core::ruby_version::tests::test_get_ruby_stack_trace_2_7_2 ... ok
test tests::test_arg_parsing ... ok
test tests::test_report_arg_parsing ... ok
test ui::callgrind::tests::stats_aggregate ... ok
test ui::callgrind::tests::stats_write ... ok
test ui::flamegraph::tests::test_collapsed ... ok
test ui::flamegraph::tests::test_flamegraph_from_collapsed ... ok
test ui::flamegraph::tests::test_stats ... ok
test ui::summary::tests::stats_by_function ... ok
test ui::summary::tests::stats_by_line_number ... ok
test core::ruby_version::tests::test_get_ruby_stack_trace_2_7_4 ... ok
test core::ruby_version::tests::test_get_ruby_stack_trace_3_0_0 ... ok
test core::ruby_version::tests::test_get_ruby_stack_trace_2_7_3 ... ok
test core::ruby_version::tests::test_get_ruby_stack_trace_3_0_2 ... ok
test core::ruby_version::tests::test_get_ruby_stack_trace_3_0_1 ... ok
test core::ruby_version::tests::test_get_ruby_stack_trace_2_1_6_2 ... ok
test test_spawn_record_children_subprocesses ... FAILED

failures:

---- core::initialize::test_get_trace stdout ----
thread 'core::initialize::test_get_trace' panicked at 'called `Result::unwrap()` on an `Err` value: get ruby VM state

Caused by:
    Couldn't get ruby version: get Ruby version

    Caused by:
        0: get_ruby_version_address
        1: Ruby map not found for PID: 3205454', src/core/initialize.rs:329:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- core::initialize::test_get_exec_trace stdout ----
thread 'core::initialize::test_get_exec_trace' panicked at 'initialize: get ruby VM state

Caused by:
    Couldn't get ruby version: get Ruby version

    Caused by:
        0: get_ruby_version_address
        1: Ruby map not found for PID: 3205452', src/core/initialize.rs:351:44

---- core::initialize::test_current_thread_address stdout ----
thread 'core::initialize::test_current_thread_address' panicked at 'couldn't get ruby version', src/core/initialize.rs:304:13

---- test_spawn_record_children_subprocesses stdout ----
Press Ctrl+C to stop
thread 'test_spawn_record_children_subprocesses' panicked at 'unexpected error: get ruby VM state

Caused by:
    Couldn't get ruby version: get Ruby version

    Caused by:
        0: get_ruby_version_address
        1: Ruby map not found for PID: 3205560', src/main.rs:567:11


failures:
    core::initialize::test_current_thread_address
    core::initialize::test_get_exec_trace
    core::initialize::test_get_trace
    test_spawn_record_children_subprocesses

test result: FAILED. 23 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.21s
```

Due to panic, and processes not being killed, some of the processes are still running

`% ps a`

```
...
3205451 pts/8    S      0:00 ruby ./ci/ruby-programs/infinite.rb
3205454 pts/8    S      0:00 ruby ./ci/ruby-programs/infinite.rb
3205548 pts/8    S      0:00 ruby ci/ruby-programs/ruby_forks.rb $USER/tmp/EQ3YmrowTV2q
...
3205829 pts/8    S      0:00 $USER/.rbenv/versions/2.6.7/bin/ruby -e   pid1_1 = spawn(ENV,
3205830 pts/8    S      0:00 $USER/.rbenv/versions/2.6.7/bin/ruby -e    while !File.exists?
3205843 pts/8    S      0:00 $USER/.rbenv/versions/2.6.7/bin/ruby -e    while !File.exists?
```

**Comment by Horki** [comment]
@acj is this fixed now?

**Comment by Horki** [comment]
@acj it's not, please re-open

**Comment by acj** [comment]
I'm not able to reproduce the orphaned process issue in my VM (Ubuntu 20.10, Ruby 2.7.4) anymore. Could you please post updated output from your test run? Also, which Ruby version and Linux distribution are you using?
