### ISSUE TITLE
Profiling multiple subprocesses fails in 0.12.1

### ISSUE THREAD

**Issue by viraptor** [rbspy/rbspy#367]
If I run the profiling of a multiprocess app for a while (in this case unicorn workers), I get the following crash:

```
thread '<unnamed>' panicked at 'couldn't send error: SendError { .. }', src/sampler/mod.rs:121:56
stack backtrace:
thread '<unnamed>' panicked at 'couldn't send error: SendError { .. }', src/sampler/mod.rs:121:56
thread '<unnamed>' panicked at 'couldn't send error: SendError { .. }', src/sampler/mod.rs:121:56
thread '<unnamed>' panicked at 'couldn't send error: SendError { .. }', src/sampler/mod.rs:121:56
thread '<unnamed>' panicked at 'couldn't send error: SendError { .. }', src/sampler/mod.rs:121:56
thread '<unnamed>' panicked at 'couldn't send error: SendError { .. }', src/sampler/mod.rs:121:56
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
thread '<unnamed>' panicked at 'couldn't send error: SendError { .. }', src/sampler/mod.rs:121:56
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Wrote raw data to (...)/.cache/rbspy/2022-05-11-ABoIC2c980.raw.gz
Wrote formatted output to output.pb
Something went wrong while rbspy was sampling the process. Here's what we know:
- second time provided was later than self
```

The collection is running with `./rbspy-x86_64-musl record -p 23924 -s --nonblocking -f output.pb -o pprof -r 50` against ruby 2.7. This happens every time, after at most 10s.

The same issue does not happen if I remove subprocess profiling.

**Comment by acj** [comment]
I'm not able to reproduce this. What distro/version of Linux are you running? And does the panic still happen if you remove `--nonblocking`?

**Comment by viraptor** [comment]
Sorry, forgot about this one. Yes, I can reproduce this with and without `nonblocking`.
