### ISSUE TITLE
[mac-support] 2 tests fail with "Expected NoSuchProcess error"

### ISSUE THREAD

**Issue by thbar** [rbspy/rbspy#72]
On High Sierra, I get this failure (while investigating on #70):

```
10:24 $ RUST_BACKTRACE=1 cargo test test_get_nonexistent_process
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/rbspy-212acef39ff53d5d

running 1 test
test initialize::test_get_nonexistent_process ... FAILED

failures:

---- initialize::test_get_nonexistent_process stdout ----
	Before task_for_pid
After task_for_pid
thread 'initialize::test_get_nonexistent_process' panicked at 'Expected NoSuchProcess error', src/initialize.rs:141:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:57
             at src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:391
   4: std::panicking::begin_panic
             at src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:538
   6: rbspy::initialize::test_get_nonexistent_process
             at src/initialize.rs:141
   7: <F as test::FnBox<T>>::call_box
             at src/libtest/lib.rs:1510
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at src/libtest/lib.rs:142
   8: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:101


failures:
    initialize::test_get_nonexistent_process

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 10 filtered out
```

Another test fails with a similar error:

```
10:25 $ RUST_BACKTRACE=1 cargo test test_get_disallowed_process
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/rbspy-212acef39ff53d5d

running 1 test
test initialize::test_get_disallowed_process ... FAILED

failures:

---- initialize::test_get_disallowed_process stdout ----
	Before task_for_pid
After task_for_pid
thread 'initialize::test_get_disallowed_process' panicked at 'Expected NoSuchProcess error', src/initialize.rs:155:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:57
             at src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:391
   4: std::panicking::begin_panic
             at src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:538
   6: rbspy::initialize::test_get_disallowed_process
             at src/initialize.rs:155
   7: <F as test::FnBox<T>>::call_box
             at src/libtest/lib.rs:1510
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at src/libtest/lib.rs:142
   8: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:101


failures:
    initialize::test_get_disallowed_process

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 10 filtered out
```

**Comment by jvns** [comment]
thanks! I suspect I just need to write different tests for Mac and Linux.

**Comment by thbar** [comment]
@jvns ok! Do you prefer me to close the issue for now as well as #73, or should I keep those opened?

**Comment by jvns** [comment]
Should be fixed now!
