### ISSUE TITLE
[mac] panicked at 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by parkr** [rbspy/rbspy#87]
I'm using rbspy at 6f2ca058133835ece6e0ff2087e96be7f2ab6844! I was trying to profile `jekyll build` and I got a neat panic! It appears to be happening when it tries to get the line number in a sample.

```text
thread 'main' panicked at 'attempt to subtract with overflow', src/ruby_version.rs:402:27
```

L402 is in this block (`let mut pos = ...`)!

https://github.com/rbspy/rbspy/blob/6f2ca058133835ece6e0ff2087e96be7f2ab6844/src/ruby_version.rs#L395-L424

Full stacktrace:

```text
~/jekyll/jekyll/docs#related-posts-perf-improvements$ sudo --preserve-env env RUST_BACKTRACE=1 ~/code/rbspy/target/debug/rbspy record jekyll build
Password:
Dropping permissions: running Ruby command as user parkr
Recording data to /Users/parkr/.cache/rbspy/records/rbspy-2018-02-01-LHsUZJfleM.txt
Press Ctrl+C to stop
Configuration file: /Users/parkr/jekyll/jekyll/docs/_config.yml
            Source: /Users/parkr/jekyll/jekyll/docs
       Destination: /Users/parkr/jekyll/jekyll/docs/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Behind expected sample time by 2338500 nanoseconds, results may be inaccurate. Try sampling at a lower rate with `--rate`. Current rate: 100.
Behind expected sample time by 306174 nanoseconds, results may be inaccurate. Try sampling at a lower rate with `--rate`. Current rate: 100.
Behind expected sample time by 14352733 nanoseconds, results may be inaccurate. Try sampling at a lower rate with `--rate`. Current rate: 100.
Behind expected sample time by 7328258 nanoseconds, results may be inaccurate. Try sampling at a lower rate with `--rate`. Current rate: 100.
Behind expected sample time by 444778 nanoseconds, results may be inaccurate. Try sampling at a lower rate with `--rate`. Current rate: 100.
thread 'main' panicked at 'attempt to subtract with overflow', src/ruby_version.rs:402:27
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:57
             at src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   4: std::panicking::begin_panic
             at src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at src/libstd/panicking.rs:538
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:522
   7: std::panicking::try::do_call
             at src/libstd/panicking.rs:498
   8: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at src/libcore/panicking.rs:71
   9: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at src/libcore/panicking.rs:51
  10: rbspy::ruby_version::ruby_2_5_0_rc1::get_lineno
             at src/ruby_version.rs:402
  11: rbspy::ruby_version::ruby_2_5_0_rc1::get_stack_frame
             at src/ruby_version.rs:473
  12: rbspy::ruby_version::ruby_2_5_0_rc1::get_stack_trace
             at src/ruby_version.rs:137
  13: core::ops::function::Fn::call
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:73
  14: rbspy::initialize::StackTraceGetter::get_trace
             at src/initialize.rs:94
  15: rbspy::record
             at src/main.rs:282
  16: rbspy::do_main
             at src/main.rs:143
  17: rbspy::main
             at src/main.rs:174
  18: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:101
  19: rust_panic
             at src/libstd/panicking.rs:459
             at src/libstd/panic.rs:365
             at src/libstd/rt.rs:58
  20: rbspy::OutputFormat::variants
~/jekyll/jekyll/docs#related-posts-perf-improvements$                     done in 9.149 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

**Comment by jvns** [comment]
Thanks! there have been a bunch of similar issues to this but looks like this one didn't get fixed yet :).  what's happening is that we're subtracting two unsigned integers (`a-b`) where b is bigger than a. this is generally because rbspy has gotten into some kind of race and it's reading invalid memory.

Basically what needs to happen is that we need to check in advance whether `cfp.pc` is less than `iseq_struct.iseq_encoded` and if so return an error (so that `record` can handle the error and try again) instead of panicking. 

if you're interested in mucking around in rbspy's internals I think this shouldn't be that hard to fix. The main issue is that it needs to be fixed in like 4 places, everywhere `cfp.pc as usize - iseq_struct.iseq_encoded` appears, Otherwise I'll put together a PR later today.

**Comment by parkr** [comment]
Thank you! 💗 ✨ I'm sorry I wasn't able to get to it – I am interested in contributing in the future, but it's been an abnormally busy few days.

**Comment by jvns** [comment]
totally understand! i'm basically working on this full time so I have an abnormal amount of time :). if/when you're interested in getting started developing rbspy I'd be happy to help!
